version: "3.9"

services:
  prefect-server:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect-server
    ports:
      - "4200:4200"
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    restart: unless-stopped